openapi: 3.0.0
info:
  title: Sample API
  version: "1.0"
  description: A simple API with Bearer token authentication

paths:
  /items:
    get:
      summary: List all items
      security:
        - BearerAuth: []
      responses:
        "200":
          description: A JSON array of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      summary: Create a new item
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "201":
          description: The created item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"

  /items/{id}:
    get:
      summary: Get a specific item by ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "404":
          description: Item not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
